version: "3.9"

secrets:
  github-ci-secret.sh:
    external: true

services:
  jsonpath-faster-runner:
    image: stilt:5000/jsonpath-faster-runner-${ARCH}
    build:
      context: .
    restart: unless-stopped
    environment:
      USER: AndyA
      REPO: jsonpath-faster
    secrets:
      - github-ci-secret.sh
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 256M
  jsonpath-lifter-runner:
    image: stilt:5000/jsonpath-lifter-runner-${ARCH}
    build:
      context: .
    restart: unless-stopped
    environment:
      USER: AndyA
      REPO: jsonpath-lifter
    secrets:
      - github-ci-secret.sh
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 256M
  node-bktree-fast-runner:
    image: stilt:5000/node-bktree-fast-runner-${ARCH}
    build:
      context: .
    restart: unless-stopped
    environment:
      USER: AndyA
      REPO: node-bktree-fast
    secrets:
      - github-ci-secret.sh
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 256M
  encoding-sleuth-runner:
    image: stilt:5000/encoding-sleuth-runner-${ARCH}
    build:
      context: .
    restart: unless-stopped
    environment:
      USER: AndyA
      REPO: encoding-sleuth
    secrets:
      - github-ci-secret.sh
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 256M
  state-sequence-store-runner: 
    image: stilt:5000/state-sequence-store-runner-${ARCH}
    build:
      context: .
    restart: unless-stopped
    environment:
      USER: AndyA
      REPO: state-sequence-store
    secrets:
      - github-ci-secret.sh
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 256M
